import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import QueryProvider from "../components/QueryProvider";
import Providers from "../components/Providers";
import { Toaster } from "react-hot-toast";
import { Hind_Siliguri } from "next/font/google";

const siliguri = Hind_Siliguri({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Craft Skills",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${siliguri.className}` }>
        <>
          <ThemeProvider>
            <QueryProvider>
              <Providers>
                <Toaster position="top-center" reverseOrder={false} />
                {children}
              </Providers>
            </QueryProvider>
          </ThemeProvider>
        </>
      </body>
    </html>
  );
}
